export type University = {
  name: string;
  location: string;
  abbreviation: string;
  [x: string]: any;
};

export const UNIVERSITIES: University[] = [
  {
    id: 0,
    name: "Other",
    abbreviation: "Other",
    location: "",
  },
  {
    id: 1,
    name: "University of Zambia",
    abbreviation: "UNZA",
    location: "Lusaka",
  },
  {
    id: 2,
    name: "ZCAS University",
    abbreviation: "ZCAS",
    location: "Lusaka",
  },
  {
    id: 3,
    name: "Mulungushi University (Lusaka Campus)",
    abbreviation: "MU",
    location: "Lusaka",
  },
  {
    id: 4,
    name: "Levy Mwanawasa Medical University",
    abbreviation: "LMMU",
    location: "Lusaka",
  },
  {
    id: 5,
    name: "Cavendish University",
    abbreviation: "CU",
    location: "Lusaka",
  },
  {
    id: 6,
    name: "Chalimbana University",
    abbreviation: "CHAU",
    location: "Lusaka",
  },
  {
    id: 7,
    name: "Eden University",
    abbreviation: "EU",
    location: "Lusaka",
  },
  {
    id: 8,
    name: "DMI St. Eugene University",
    abbreviation: "DMI",
    location: "Lusaka",
  },
  {
    id: 9,
    name: "Livingstone International University for Tourism Excellence and Business Management",
    abbreviation: "LIUTEBM",
    location: "Lusaka",
  },
  {
    id: 10,
    name: "Texila American University",
    abbreviation: "TAU",
    location: "Lusaka",
  },
  {
    id: 11,
    name: "Lusaka Apex Medical University",
    abbreviation: "LAMU",
    location: "Lusaka",
  },
  {
    id: 12,
    name: "Rockview University",
    abbreviation: "Rockview",
    location: "Lusaka",
  },
  {
    id: 13,
    name: "Evelyn Hone College of Applied Arts and Commerce",
    abbreviation: "Evelyn Hone",
    location: "Lusaka",
  },
  {
    id: 14,
    name: "Chreso University",
    abbreviation: "Chreso",
    location: "Lusaka",
  },
  {
    id: 15,
    name: "Lusaka Business and Technical College",
    abbreviation: "LBTC",
    location: "Lusaka",
  },
  {
    id: 16,
    name: "National Institute of Public Administration",
    abbreviation: "NIPA",
    location: "Lusaka",
  },
  {
    id: 17,
    name: "Zambia Institute of Management",
    abbreviation: "ZAMIM",
    location: "Lusaka",
  },
  {
    id: 18,
    name: "Lusaka Vocational Training Centre",
    abbreviation: "LVTC",
    location: "Lusaka",
  },
  {
    id: 19,
    name: "Paglory University",
    abbreviation: "Paglory",
    location: "Lusaka",
  },
  {
    id: 20,
    name: "Zambian Royal Medical University",
    abbreviation: "ZRMU",
    location: "Lusaka",
  },
  {
    id: 21,
    name: "Zambian Open University",
    abbreviation: "ZAOU",
    location: "Lusaka",
  },
  {
    id: 22,
    name: "Justo Mwale University",
    abbreviation: "JMU",
    location: "Lusaka",
  },
  {
    id: 23,
    name: "Zambia Institute of Legal Studies",
    abbreviation: "ZILS",
    location: "Lusaka",
  },
  {
    id: 24,
    name: "Rusangu University",
    abbreviation: "RU",
    location: "Lusaka",
  },
  {
    id: 25,
    name: "Makeni College",
    abbreviation: "Makeni",
    location: "Lusaka",
  },
  {
    id: 26,
    name: "Greenfield University",
    abbreviation: "GFU",
    location: "Lusaka",
  },
  {
    id: 27,
    name: "City University of Science and Technology",
    abbreviation: "CUST",
    location: "Lusaka",
  },
  {
    id: 28,
    name: "George Benson Christian College",
    abbreviation: "GBCC",
    location: "Lusaka",
  },
  {
    id: 29,
    name: "Zambia Catholic University (Lusaka Campus)",
    abbreviation: "ZCU",
    location: "Lusaka",
  },
  {
    id: 30,
    name: "Fairview College of Education",
    abbreviation: "Fairview",
    location: "Lusaka",
  },
  {
    id: 31,
    name: "St. Bonaventure University",
    abbreviation: "SBU",
    location: "Lusaka",
  },
  {
    id: 32,
    name: "University of Lusaka",
    abbreviation: "UNILUS",
    location: "Lusaka",
  },
  {
    id: 33,
    name: "Chilubula College of Nursing",
    abbreviation: "CCN",
    location: "Lusaka",
  },
  {
    id: 34,
    name: "Mwaleshi University",
    abbreviation: "MWU",
    location: "Lusaka",
  },
  {
    id: 35,
    name: "Malcolm Moffat College of Education",
    abbreviation: "MMCE",
    location: "Lusaka",
  },
  {
    id: 36,
    name: "Copperstone University",
    abbreviation: "Copperstone",
    location: "Lusaka",
  },
  {
    id: 37,
    name: "African Christian University",
    abbreviation: "ACU",
    location: "Lusaka",
  },
  {
    id: 38,
    name: "Institute of Health Sciences",
    abbreviation: "IHS",
    location: "Lusaka",
  },
  {
    id: 39,
    name: "Mufulira Professional College",
    abbreviation: "MPC",
    location: "Lusaka",
  },
  {
    id: 40,
    name: "Lusaka School of Nursing",
    abbreviation: "LSN",
    location: "Lusaka",
  },
  {
    id: 41,
    name: "Technical University of Zambia",
    abbreviation: "TUZ",
    location: "Lusaka",
  },
  {
    id: 42,
    name: "Valley View University",
    abbreviation: "VVU",
    location: "Lusaka",
  },
  {
    id: 43,
    name: "St. Paul’s School of Nursing",
    abbreviation: "St. Paul",
    location: "Lusaka",
  },
  {
    id: 44,
    name: "Zambia College of Health Sciences",
    abbreviation: "ZCHS",
    location: "Lusaka",
  },
  {
    id: 45,
    name: "Horizon University",
    abbreviation: "HU",
    location: "Lusaka",
  },
  {
    id: 46,
    name: "Rusangu University (Lusaka Campus)",
    abbreviation: "RU-Lusaka",
    location: "Lusaka",
  },
  {
    id: 47,
    name: "International School of Lusaka",
    abbreviation: "ISL",
    location: "Lusaka",
  },
  {
    id: 48,
    name: "Zambian Royal Medical University",
    abbreviation: "ZRMU",
    location: "Lusaka",
  },
  {
    id: 49,
    name: "Olympia Park College",
    abbreviation: "OPC",
    location: "Lusaka",
  },
  {
    id: 50,
    name: "Mulungushi University (Main Campus)",
    abbreviation: "MU-Main",
    location: "Kabwe",
  },
  {
    id: 51,
    name: "Copperbelt University",
    abbreviation: "CBU",
    location: "Kitwe",
  },
];
